#12-properties manager
Meisterwerk-GmbH/bq-utils pull request #15
Opened 2023-07-27 09:36 UTC by SaraLuethi

#12 

muss man dann noch in bq-post-print einbauen

2023-07-27 12:14 UTC, 71m024 requested changes
Finde das eine gute klasse. Aber bitte noch einmal etwas überarbeiten und jeweils via Link testen, bevor du einen PR machst.

2023-07-27 12:14 UTC, 71m024 commented on src/BqPropertiesManager.php
> +    private const BQ_API_PATH_V3 = 'https://rentshop.booqable.com/api/3/';
Bitte diese Konstanten löschen.  
Dieses Repo ist public und nicht rentshop spezifisch.

2023-07-27 12:14 UTC, 71m024 commented on src/BqPropertiesManager.php
> +    }
Bitte lass dir die beiden Managers als Parameter übergeben und erstelle sie nicht selber.

2023-07-27 12:14 UTC, 71m024 commented on src/BqPropertiesManager.php
> +    public function createOrUpdateProperty(string $bqOrderId, string $value, array $propertyFields): void
Bitte `propertyFields` zu `propertyQuery` umbenennen und dafür eine Klasse machen (`BqOrderPropertyQuery`).  
Diese Klasse dann grad zusammen mit dem Manager in ein neues Package `OrderProperties`  verschieben.

2023-07-27 12:14 UTC, 71m024 commented on src/BqPropertiesManager.php
> +class BqPropertiesManager
Bitte umbenennen zu `BqOrderPropertiesManager`

2023-07-27 12:14 UTC, 71m024 commented on src/BqPropertiesManager.php
> +    public function createOrUpdateProperty(string $bqOrderId, string $value, array $propertyFields): void
Parameteter `$bqOrderId` bitte zu `orderId` umbenennen. Mach es nicht unnötig kompliziert.

2023-07-27 12:14 UTC, 71m024 commented on src/BqPropertiesManager.php
> +        }
Hier muss noch eine Exception geworfen werden, wenn das Property nicht eindeutig gefunden wird.

2023-07-27 15:00 UTC, SaraLuethi commented
@71m024 ist in bq-post-print eingebaut, bzw. mit dem getestet worden. Schaust du es noch einmal an? Dann mache in den PR von bq-post-print nachdem das hier gemergt ist.

2023-07-28 07:50 UTC, 71m024 approved these changes

2023-07-28 07:52 UTC, merged