shopify-booqable #80
Meisterwerk-GmbH/bq-utils pull request #20
Opened 2023-09-14 14:26 UTC by SaraLuethi

shopify-booqable: https://github.com/Meisterwerk-GmbH/shopify-booqable/issues/80

2023-09-15 08:29 UTC, 71m024 requested changes
Warum hast du den type zum query hinzufgefügt???   
Den braucht man doch nicht da?

2023-09-15 12:45 UTC, SaraLuethi commented
@71m024 habe es angepasst, schaust du es noch einmal an? 
Was meint du mit "Bitte einen PR im bq-util machen." --> den gibt es ja bereits

2023-09-18 13:39 UTC, 71m024 requested changes

2023-09-18 13:39 UTC, 71m024 commented on src/OrderProperties/BqOrderPropertiesManager.php
>                  $propertyToSet->id
Aus meiner Sich braucht es diese drei Parameter nicht. Bitte durch das `propertyToSet` ersetzen.

2023-09-18 13:39 UTC, 71m024 commented on src/OrderProperties/BqOrderPropertiesManager.php
>          } elseif (count($filteredProperties) > 1) {
Bitte Else und Else-If vertauschen.

2023-09-19 09:03 UTC, merged